export const ADD_IMAGE = 'ADD_IMAGE';
export const GET_LIBRARY_DATA = 'GET_LIBRARY_DATA';
export const GET_LIBRARY_ALBUMS = 'GET_LIBRARY_ALBUMS';
export const GET_LIBRARY_PHOTOS = 'GET_LIBRARY_PHOTOS';
