/* post */
export const LOAD_POSTS = 'LOAD_POSTS';
export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_POST = 'ADD_POST';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';

/* library */
export const GET_LIBRARY_DATA = 'GET_LIBRARY_DATA';
export const GET_LIBRARY_ALBUMS = 'GET_LIBRARY_ALBUMS';
export const GET_LIBRARY_PHOTOS = 'GET_LIBRARY_PHOTOS';
export const SET_PHOTOS_FOR_EDITING = 'SET_PHOTOS_FOR_EDITING';
export const SET_PHOTO_TO_SAVE = 'SET_PHOTO_TO_SAVE';
export const SET_PHOTO_TO_SHARE = 'SET_PHOTO_TO_SHARE';
export const SET_TEXT_TO_SHARE = 'SET_TEXT_TO_SHARE';
export const RESET_DATA_FOR_SHARING = 'RESET_DATA_FOR_SHARING';
