export const ADD_IMAGE = 'ADD_IMAGE';
export const GET_LIBRARY_DATA = 'GET_LIBRARY_DATA';
export const GET_LIBRARY_ALBUMS = 'GET_LIBRARY_ALBUMS';
export const GET_LIBRARY_PHOTOS = 'GET_LIBRARY_PHOTOS';
export const SET_PHOTOS_FOR_EDITING = 'SET_PHOTOS_FOR_EDITING';
export const SET_PHOTO_TO_SAVE = 'SET_PHOTO_TO_SAVE';
export const SET_PHOTO_TO_SHARE = 'SET_PHOTO_TO_SHARE';
